# Generated by Django 2.2.2 on 2019-07-16 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0019_auto_20190702_1406'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
